---
- hosts: "masters, nodes"
  remote_user: kube
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: update and upgrade apt packages
       shell: |
              sudo apt update && sudo apt full-upgrade -y
